### ISSUE TITLE
False number of votes 

### ISSUE THREAD

**Issue by vibe123456** [babolivier/matrix-poll-bot#15]
Hello everybody,

first of all, thank you very much for this poll-bot! 
We use it regulary, but i got the impression, that the poll-bot has a small bug. When starting a new poll, the number of replys per answer is automatically set to 1 per each answer, or am i wrong?
Thank you in advance!
David

**Comment by wyldeTurkey** [comment]
That's my experience with it as well. All options automatically start out with a value of 1 when it should be zero. 

Additionally it permits users to vote on all options and the options seem to be limited to 3. maybe i'm wrong but that's what my initial testing shows.

**Comment by wyldeTurkey** [comment]
Indeed. I get the same behavior as well. It appears that for the bot to present the options of the emojis to the other users in the room, it has to also apply the emoji's to the "poll" (message event). because of how the underlying code works, it necessarily starts out with a value of 1.
For now, i'm just having to mouse over the options and see who's voting for what. If i see the ID of my poll-bot i subtract 1 from that value in my head. The only solution i can see is that the bot removes it's emoji to the poll choice if someone else applies votes for the same poll choice. obviously, this could get confusing for people if they're the first person to click an option and it remains 1 despite their vote they're likely to think it's bugged (it is, kind of). 

The other glaring issue is that it lets users vote on more than one option. no idea whatsoever on how to fix that one. You'd have to manually police the votes and see who voted twice and talk to them individually if it's important.
