### ISSUE TITLE
Rating system based on single items room polls with aggregated widget

### ISSUE THREAD

**Issue by MurzNN** [babolivier/matrix-poll-bot#7]
Some rooms need the rating tool, that aggregate several poll items (each item is single message) and build rating list of all items.

For example, in movies discussion room people want to build film raiting list, where people can vote up/down items, that already added by other users, and add new items.

This can be implemented via commands like `!room-poll add <Item text>` and reactions on this message.

For visualize results will be best to use Matrix room widget iframe window, that aggregate all messages from room to ordered, list and show uservotes for each item.

**Comment by babolivier** [comment]
I'm not really sure about that, tbh. I made this poll (as most of my projects) following the Unix philosophy (do one thing and do it well, in this case polls), and I'm not sure I like the complexity such a feature would add to the bot.
I might change my mind on this item and implement it in the future, but can't make any promise about that.
It's worth noting that, because of that same argument of keeping it simple, building on top of it to make a rating system (for example) can be fairly easy, as the entire database of polls and votes only consists in part of the room's timeline.

**Comment by MurzNN** [comment]
Yes, this looks more like separate tool, than extending current poll bot, thanks for describing! Let's close it.
